# Generated by Django 4.2.7 on 2023-11-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_oders'),
    ]

    operations = [
        migrations.AddField(
            model_name='oders',
            name='total',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
